//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isogeo.Language {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Isogeo.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action type.
        /// </summary>
        public static string Action_type {
            get {
                return ResourceManager.GetString("Action_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action type (default).
        /// </summary>
        public static string Action_type_default {
            get {
                return ResourceManager.GetString("Action_type_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download.
        /// </summary>
        public static string Action_type_download {
            get {
                return ResourceManager.GetString("Action_type_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View.
        /// </summary>
        public static string Action_type_view {
            get {
                return ResourceManager.GetString("Action_type_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advanced search.
        /// </summary>
        public static string Advanced_search {
            get {
                return ResourceManager.GetString("Advanced_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alias.
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alternative login.
        /// </summary>
        public static string Alternative_login {
            get {
                return ResourceManager.GetString("Alternative_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application ID.
        /// </summary>
        public static string Application_ID {
            get {
                return ResourceManager.GetString("Application_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application SECRET.
        /// </summary>
        public static string Application_SECRET {
            get {
                return ResourceManager.GetString("Application_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentication settings.
        /// </summary>
        public static string Authentication_settings {
            get {
                return ResourceManager.GetString("Authentication_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Isogeo authentication settings.
        /// </summary>
        public static string Authentication_Title {
            get {
                return ResourceManager.GetString("Authentication_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t be added.
        /// </summary>
        public static string Cant_be_added {
            get {
                return ResourceManager.GetString("Cant_be_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conform.
        /// </summary>
        public static string Conform {
            get {
                return ResourceManager.GetString("Conform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact support.
        /// </summary>
        public static string Contact_support {
            get {
                return ResourceManager.GetString("Contact_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordinate system.
        /// </summary>
        public static string Coordinate_system_source {
            get {
                return ResourceManager.GetString("Coordinate_system_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conception.
        /// </summary>
        public static string Credit_conception {
            get {
                return ResourceManager.GetString("Credit_conception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contents.
        /// </summary>
        public static string Credit_contenu {
            get {
                return ResourceManager.GetString("Credit_contenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Made by freelance developer Vianney DOLEANS.
        /// </summary>
        public static string Credit_contenu_label {
            get {
                return ResourceManager.GetString("Credit_contenu_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Development Contributors :.
        /// </summary>
        public static string Credit_developedby {
            get {
                return ResourceManager.GetString("Credit_developedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Development.
        /// </summary>
        public static string Credit_development {
            get {
                return ResourceManager.GetString("Credit_development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Isogeo - all right reserved.
        /// </summary>
        public static string Credit_isogeo {
            get {
                return ResourceManager.GetString("Credit_isogeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plugin Isogeo - Credits.
        /// </summary>
        public static string Credit_title {
            get {
                return ResourceManager.GetString("Credit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data file.
        /// </summary>
        public static string Data_file {
            get {
                return ResourceManager.GetString("Data_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default search.
        /// </summary>
        public static string Default_search {
            get {
                return ResourceManager.GetString("Default_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default sort order.
        /// </summary>
        public static string Default_sort_order {
            get {
                return ResourceManager.GetString("Default_sort_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string Define_as_default_search {
            get {
                return ResourceManager.GetString("Define_as_default_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t have an access?.
        /// </summary>
        public static string Dont_have_an_access {
            get {
                return ResourceManager.GetString("Dont_have_an_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string en_EN {
            get {
                return ResourceManager.GetString("en-EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Metadata has not been properly completed.
        /// </summary>
        public static string Error_bad_metadata {
            get {
                return ResourceManager.GetString("Error_bad_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Can&apos;t contact support by email.
        /// </summary>
        public static string Error_contact_support {
            get {
                return ResourceManager.GetString("Error_contact_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Invalid data, map can&apos;t load extent.
        /// </summary>
        public static string Error_extent_map {
            get {
                return ResourceManager.GetString("Error_extent_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Can&apos;t load log Manager.
        /// </summary>
        public static string Error_logManager {
            get {
                return ResourceManager.GetString("Error_logManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Can&apos;t load log file.
        /// </summary>
        public static string Error_logs {
            get {
                return ResourceManager.GetString("Error_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proxy information could not be saved.
        /// </summary>
        public static string Error_proxy {
            get {
                return ResourceManager.GetString("Error_proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SDE connection file.
        /// </summary>
        public static string FileSDE {
            get {
                return ResourceManager.GetString("FileSDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format.
        /// </summary>
        public static string Format_source {
            get {
                return ResourceManager.GetString("Format_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string fr_FR {
            get {
                return ResourceManager.GetString("fr-FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Geographic filter.
        /// </summary>
        public static string Geographic_filter {
            get {
                return ResourceManager.GetString("Geographic_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contains.
        /// </summary>
        public static string Geographic_type_contains {
            get {
                return ResourceManager.GetString("Geographic_type_contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intersect.
        /// </summary>
        public static string Geographic_type_intersects {
            get {
                return ResourceManager.GetString("Geographic_type_intersects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Whithin.
        /// </summary>
        public static string Geographic_type_within {
            get {
                return ResourceManager.GetString("Geographic_type_within", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Geographical operator.
        /// </summary>
        public static string Geographical_operator_applied_to_the_filter {
            get {
                return ResourceManager.GetString("Geographical_operator_applied_to_the_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import access from a file :.
        /// </summary>
        public static string Import_access_from_a_file {
            get {
                return ResourceManager.GetString("Import_access_from_a_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import file.
        /// </summary>
        public static string Import_File {
            get {
                return ResourceManager.GetString("Import_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à INSPIRE keywords.
        /// </summary>
        public static string INSPIRE_keywords {
            get {
                return ResourceManager.GetString("INSPIRE_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Isogeo authentication settings.
        /// </summary>
        public static string Isogeo_authentication_settings {
            get {
                return ResourceManager.GetString("Isogeo_authentication_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Isogeo login.
        /// </summary>
        public static string Isogeo_login {
            get {
                return ResourceManager.GetString("Isogeo_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Isogeo Metadata.
        /// </summary>
        public static string Isogeo_Metadata {
            get {
                return ResourceManager.GetString("Isogeo_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (default).
        /// </summary>
        public static string Lang_default {
            get {
                return ResourceManager.GetString("Lang_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licence.
        /// </summary>
        public static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log path : .
        /// </summary>
        public static string Log_path {
            get {
                return ResourceManager.GetString("Log_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Map canvas.
        /// </summary>
        public static string Map_canvas {
            get {
                return ResourceManager.GetString("Map_canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download.
        /// </summary>
        public static string Menu_Download {
            get {
                return ResourceManager.GetString("Menu_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load data.
        /// </summary>
        public static string Menu_load {
            get {
                return ResourceManager.GetString("Menu_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Metadata.
        /// </summary>
        public static string Menu_Metadata {
            get {
                return ResourceManager.GetString("Menu_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OpenCatalog.
        /// </summary>
        public static string Menu_OpenCatalog {
            get {
                return ResourceManager.GetString("Menu_OpenCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can contact support at &apos;support+arcgispro@isogeo.fr&apos;.
        /// </summary>
        public static string Message_contact_support {
            get {
                return ResourceManager.GetString("Message_contact_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The requested service is not compatible or has not been configured to work in ArcGis Pro.
        /// </summary>
        public static string Message_Data_Error {
            get {
                return ResourceManager.GetString("Message_Data_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File is not found.
        /// </summary>
        public static string Message_Data_file_not_found {
            get {
                return ResourceManager.GetString("Message_Data_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Layer not found.
        /// </summary>
        public static string Message_Data_layer_not_found {
            get {
                return ResourceManager.GetString("Message_Data_layer_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SDE login file not configured in the &apos;Settings&apos; tab..
        /// </summary>
        public static string Message_Data_sde_not_configured {
            get {
                return ResourceManager.GetString("Message_Data_sde_not_configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Table name is undefined.
        /// </summary>
        public static string Message_Data_table_undefined {
            get {
                return ResourceManager.GetString("Message_Data_table_undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unmanaged data type.
        /// </summary>
        public static string Message_Data_Type {
            get {
                return ResourceManager.GetString("Message_Data_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advanced.
        /// </summary>
        public static string Message_Metadata_Advanced {
            get {
                return ResourceManager.GetString("Message_Metadata_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contacts.
        /// </summary>
        public static string Message_Metadata_Contacts {
            get {
                return ResourceManager.GetString("Message_Metadata_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General.
        /// </summary>
        public static string Message_Metadata_General {
            get {
                return ResourceManager.GetString("Message_Metadata_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Geography.
        /// </summary>
        public static string Message_Metadata_Geography {
            get {
                return ResourceManager.GetString("Message_Metadata_Geography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à History.
        /// </summary>
        public static string Message_Metadata_History {
            get {
                return ResourceManager.GetString("Message_Metadata_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licenses.
        /// </summary>
        public static string Message_Metadata_Licenses {
            get {
                return ResourceManager.GetString("Message_Metadata_Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID is mandatory.
        /// </summary>
        public static string Message_Query_authentication_id_mandatory {
            get {
                return ResourceManager.GetString("Message_Query_authentication_id_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion failed..
        /// </summary>
        public static string Message_Query_authentication_ko {
            get {
                return ResourceManager.GetString("Message_Query_authentication_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection failed. Please check your internet connection and try again..
        /// </summary>
        public static string Message_Query_authentication_ko_internet {
            get {
                return ResourceManager.GetString("Message_Query_authentication_ko_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid ID or SECRET.
        /// </summary>
        public static string Message_Query_authentication_ko_invalid {
            get {
                return ResourceManager.GetString("Message_Query_authentication_ko_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection failed. Please check your proxy parameters.
        /// </summary>
        public static string Message_Query_authentication_ko_proxy {
            get {
                return ResourceManager.GetString("Message_Query_authentication_ko_proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion is ok..
        /// </summary>
        public static string Message_Query_authentication_ok {
            get {
                return ResourceManager.GetString("Message_Query_authentication_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SECRET must have 64 characters.
        /// </summary>
        public static string Message_Query_authentication_secret_mandatory {
            get {
                return ResourceManager.GetString("Message_Query_authentication_secret_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings saved.
        /// </summary>
        public static string Message_Settings_save {
            get {
                return ResourceManager.GetString("Message_Settings_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Created :.
        /// </summary>
        public static string Metadata_Advanced_create {
            get {
                return ResourceManager.GetString("Metadata_Advanced_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Metadata properties.
        /// </summary>
        public static string Metadata_Advanced_details {
            get {
                return ResourceManager.GetString("Metadata_Advanced_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language :.
        /// </summary>
        public static string Metadata_Advanced_lang {
            get {
                return ResourceManager.GetString("Metadata_Advanced_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last update :.
        /// </summary>
        public static string Metadata_Advanced_last_update {
            get {
                return ResourceManager.GetString("Metadata_Advanced_last_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Owner.
        /// </summary>
        public static string Metadata_Advanced_owner {
            get {
                return ResourceManager.GetString("Metadata_Advanced_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Other contacts.
        /// </summary>
        public static string Metadata_Contacts_others_contacts {
            get {
                return ResourceManager.GetString("Metadata_Contacts_others_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Point of contact.
        /// </summary>
        public static string Metadata_Contacts_points_contacts {
            get {
                return ResourceManager.GetString("Metadata_Contacts_points_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conformity :.
        /// </summary>
        public static string Metadata_General_conformity {
            get {
                return ResourceManager.GetString("Metadata_General_conformity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description :.
        /// </summary>
        public static string Metadata_General_description {
            get {
                return ResourceManager.GetString("Metadata_General_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keywords :.
        /// </summary>
        public static string Metadata_General_keywords {
            get {
                return ResourceManager.GetString("Metadata_General_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Owner :.
        /// </summary>
        public static string Metadata_General_owner {
            get {
                return ResourceManager.GetString("Metadata_General_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Theme :.
        /// </summary>
        public static string Metadata_General_themes {
            get {
                return ResourceManager.GetString("Metadata_General_themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format :.
        /// </summary>
        public static string Metadata_Geography_format {
            get {
                return ResourceManager.GetString("Metadata_Geography_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Geometry type :.
        /// </summary>
        public static string Metadata_Geography_geometrytype {
            get {
                return ResourceManager.GetString("Metadata_Geography_geometrytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technical informations.
        /// </summary>
        public static string Metadata_Geography_info {
            get {
                return ResourceManager.GetString("Metadata_Geography_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Layer name :.
        /// </summary>
        public static string Metadata_Geography_layerName {
            get {
                return ResourceManager.GetString("Metadata_Geography_layerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Features count :.
        /// </summary>
        public static string Metadata_Geography_nbobjects {
            get {
                return ResourceManager.GetString("Metadata_Geography_nbobjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resolution :.
        /// </summary>
        public static string Metadata_Geography_resolution {
            get {
                return ResourceManager.GetString("Metadata_Geography_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scale :.
        /// </summary>
        public static string Metadata_Geography_scale {
            get {
                return ResourceManager.GetString("Metadata_Geography_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specification.
        /// </summary>
        public static string Metadata_Geography_specification {
            get {
                return ResourceManager.GetString("Metadata_Geography_specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SRS :.
        /// </summary>
        public static string Metadata_Geography_srs {
            get {
                return ResourceManager.GetString("Metadata_Geography_srs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Typology.
        /// </summary>
        public static string Metadata_Geography_typology {
            get {
                return ResourceManager.GetString("Metadata_Geography_typology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comments :.
        /// </summary>
        public static string Metadata_History_comment {
            get {
                return ResourceManager.GetString("Metadata_History_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Context.
        /// </summary>
        public static string Metadata_History_context {
            get {
                return ResourceManager.GetString("Metadata_History_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation date :.
        /// </summary>
        public static string Metadata_History_datecreate {
            get {
                return ResourceManager.GetString("Metadata_History_datecreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End validity :.
        /// </summary>
        public static string Metadata_History_endvalid {
            get {
                return ResourceManager.GetString("Metadata_History_endvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data history.
        /// </summary>
        public static string Metadata_History_history {
            get {
                return ResourceManager.GetString("Metadata_History_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last update :.
        /// </summary>
        public static string Metadata_History_lastupdate {
            get {
                return ResourceManager.GetString("Metadata_History_lastupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last modifications.
        /// </summary>
        public static string Metadata_History_lastupdatedata {
            get {
                return ResourceManager.GetString("Metadata_History_lastupdatedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Method.
        /// </summary>
        public static string Metadata_History_method {
            get {
                return ResourceManager.GetString("Metadata_History_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start validity :.
        /// </summary>
        public static string Metadata_History_startvalid {
            get {
                return ResourceManager.GetString("Metadata_History_startvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updated every :.
        /// </summary>
        public static string Metadata_History_updateevery {
            get {
                return ResourceManager.GetString("Metadata_History_updateevery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Licences.
        /// </summary>
        public static string Metadata_Licences_licence {
            get {
                return ResourceManager.GetString("Metadata_Licences_licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Limitations.
        /// </summary>
        public static string Metadata_Licences_limitation {
            get {
                return ResourceManager.GetString("Metadata_Licences_limitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Metadata owner.
        /// </summary>
        public static string Metadata_owner {
            get {
                return ResourceManager.GetString("Metadata_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Metadata owner (default).
        /// </summary>
        public static string Metadata_owner_default {
            get {
                return ResourceManager.GetString("Metadata_owner_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Multi Polygon.
        /// </summary>
        public static string MultiPolygon {
            get {
                return ResourceManager.GetString("MultiPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New search.
        /// </summary>
        public static string New_search {
            get {
                return ResourceManager.GetString("New_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No licence.
        /// </summary>
        public static string No_licence {
            get {
                return ResourceManager.GetString("No_licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NR.
        /// </summary>
        public static string NotReported {
            get {
                return ResourceManager.GetString("NotReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open online help.
        /// </summary>
        public static string Open_help {
            get {
                return ResourceManager.GetString("Open_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open log file.
        /// </summary>
        public static string Open_log {
            get {
                return ResourceManager.GetString("Open_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open plugin credits.
        /// </summary>
        public static string Open_plugin_credits {
            get {
                return ResourceManager.GetString("Open_plugin_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Point.
        /// </summary>
        public static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Polygon.
        /// </summary>
        public static string Polygon {
            get {
                return ResourceManager.GetString("Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PostGIS table.
        /// </summary>
        public static string PostGIS_table {
            get {
                return ResourceManager.GetString("PostGIS_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last search.
        /// </summary>
        public static string Previous_search {
            get {
                return ResourceManager.GetString("Previous_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Proxy_password {
            get {
                return ResourceManager.GetString("Proxy_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proxy information has been saved.
        /// </summary>
        public static string Proxy_saved {
            get {
                return ResourceManager.GetString("Proxy_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proxy Settings.
        /// </summary>
        public static string Proxy_settings {
            get {
                return ResourceManager.GetString("Proxy_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proxy URL.
        /// </summary>
        public static string Proxy_url {
            get {
                return ResourceManager.GetString("Proxy_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        public static string Proxy_user {
            get {
                return ResourceManager.GetString("Proxy_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quick Search.
        /// </summary>
        public static string Quick_search {
            get {
                return ResourceManager.GetString("Quick_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quick search settings.
        /// </summary>
        public static string Quick_search_settings {
            get {
                return ResourceManager.GetString("Quick_search_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name already exist..
        /// </summary>
        public static string Quicksearch_already_exist {
            get {
                return ResourceManager.GetString("Quicksearch_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quicksearch name.
        /// </summary>
        public static string Quicksearch_name {
            get {
                return ResourceManager.GetString("Quicksearch_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name is mandatory..
        /// </summary>
        public static string Quicksearch_name_mandatory {
            get {
                return ResourceManager.GetString("Quicksearch_name_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New quicksearch.
        /// </summary>
        public static string Quicksearch_new {
            get {
                return ResourceManager.GetString("Quicksearch_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quicksearch new name.
        /// </summary>
        public static string Quicksearch_new_name {
            get {
                return ResourceManager.GetString("Quicksearch_new_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename quicksearch.
        /// </summary>
        public static string Quicksearch_rename {
            get {
                return ResourceManager.GetString("Quicksearch_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raster.
        /// </summary>
        public static string Raster {
            get {
                return ResourceManager.GetString("Raster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Realization.
        /// </summary>
        public static string Realization {
            get {
                return ResourceManager.GetString("Realization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reload last search.
        /// </summary>
        public static string Reload_last_search {
            get {
                return ResourceManager.GetString("Reload_last_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset all input fields.
        /// </summary>
        public static string Reset_search {
            get {
                return ResourceManager.GetString("Reset_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resource type.
        /// </summary>
        public static string Resource_type {
            get {
                return ResourceManager.GetString("Resource_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resources.
        /// </summary>
        public static string Resources_ {
            get {
                return ResourceManager.GetString("Resources_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save as....
        /// </summary>
        public static string Save_as {
            get {
                return ResourceManager.GetString("Save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search management.
        /// </summary>
        public static string Search_management {
            get {
                return ResourceManager.GetString("Search_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search settings.
        /// </summary>
        public static string Search_settings {
            get {
                return ResourceManager.GetString("Search_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terms search.
        /// </summary>
        public static string Search_terms {
            get {
                return ResourceManager.GetString("Search_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string Search_word {
            get {
                return ResourceManager.GetString("Search_word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set plugin authentication.
        /// </summary>
        public static string Set_pluggin_authentication {
            get {
                return ResourceManager.GetString("Set_pluggin_authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorting direction.
        /// </summary>
        public static string Sorting_direction {
            get {
                return ResourceManager.GetString("Sorting_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorting method.
        /// </summary>
        public static string Sorting_method {
            get {
                return ResourceManager.GetString("Sorting_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ascending.
        /// </summary>
        public static string Sorting_method_ascending {
            get {
                return ResourceManager.GetString("Sorting_method_ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data created.
        /// </summary>
        public static string Sorting_method_created {
            get {
                return ResourceManager.GetString("Sorting_method_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Descending.
        /// </summary>
        public static string Sorting_method_descending {
            get {
                return ResourceManager.GetString("Sorting_method_descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Metadata created.
        /// </summary>
        public static string Sorting_method_metadata_created {
            get {
                return ResourceManager.GetString("Sorting_method_metadata_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Metadata modified.
        /// </summary>
        public static string Sorting_method_metadata_modified {
            get {
                return ResourceManager.GetString("Sorting_method_metadata_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data modified.
        /// </summary>
        public static string Sorting_method_modified {
            get {
                return ResourceManager.GetString("Sorting_method_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Relevance.
        /// </summary>
        public static string Sorting_method_relevance {
            get {
                return ResourceManager.GetString("Sorting_method_relevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alphabetical order.
        /// </summary>
        public static string Sorting_method_title {
            get {
                return ResourceManager.GetString("Sorting_method_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown geometry.
        /// </summary>
        public static string Unknown_geometry {
            get {
                return ResourceManager.GetString("Unknown_geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à weeks.
        /// </summary>
        public static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WFS.
        /// </summary>
        public static string WFS {
            get {
                return ResourceManager.GetString("WFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WMS.
        /// </summary>
        public static string WMS {
            get {
                return ResourceManager.GetString("WMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WMTS.
        /// </summary>
        public static string WMTS {
            get {
                return ResourceManager.GetString("WMTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
