//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isogeo.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Isogeo.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action type.
        /// </summary>
        public static string Action_type {
            get {
                return ResourceManager.GetString("Action_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action type (default).
        /// </summary>
        public static string Action_type_default {
            get {
                return ResourceManager.GetString("Action_type_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Action_type_download {
            get {
                return ResourceManager.GetString("Action_type_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Action_type_view {
            get {
                return ResourceManager.GetString("Action_type_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced search.
        /// </summary>
        public static string Advanced_search {
            get {
                return ResourceManager.GetString("Advanced_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative login.
        /// </summary>
        public static string Alternative_login {
            get {
                return ResourceManager.GetString("Alternative_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application ID.
        /// </summary>
        public static string Application_ID {
            get {
                return ResourceManager.GetString("Application_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application SECRET.
        /// </summary>
        public static string Application_SECRET {
            get {
                return ResourceManager.GetString("Application_SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication settings.
        /// </summary>
        public static string Authentication_settings {
            get {
                return ResourceManager.GetString("Authentication_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isogeo authentication settings.
        /// </summary>
        public static string Authentication_Title {
            get {
                return ResourceManager.GetString("Authentication_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t be added.
        /// </summary>
        public static string Cant_be_added {
            get {
                return ResourceManager.GetString("Cant_be_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conform.
        /// </summary>
        public static string Conform {
            get {
                return ResourceManager.GetString("Conform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact support.
        /// </summary>
        public static string Contact_support {
            get {
                return ResourceManager.GetString("Contact_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate system.
        /// </summary>
        public static string Coordinate_system_source {
            get {
                return ResourceManager.GetString("Coordinate_system_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conception.
        /// </summary>
        public static string Credit_conception {
            get {
                return ResourceManager.GetString("Credit_conception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string Credit_contenu {
            get {
                return ResourceManager.GetString("Credit_contenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by freelance developer Vianney DOLEANS.
        /// </summary>
        public static string Credit_contenu_label {
            get {
                return ResourceManager.GetString("Credit_contenu_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Contributors :.
        /// </summary>
        public static string Credit_developedby {
            get {
                return ResourceManager.GetString("Credit_developedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Credit_development {
            get {
                return ResourceManager.GetString("Credit_development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isogeo - all right reserved.
        /// </summary>
        public static string Credit_isogeo {
            get {
                return ResourceManager.GetString("Credit_isogeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Isogeo - Credits.
        /// </summary>
        public static string Credit_title {
            get {
                return ResourceManager.GetString("Credit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data file.
        /// </summary>
        public static string Data_file {
            get {
                return ResourceManager.GetString("Data_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default search.
        /// </summary>
        public static string Default_search {
            get {
                return ResourceManager.GetString("Default_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default sort order.
        /// </summary>
        public static string Default_sort_order {
            get {
                return ResourceManager.GetString("Default_sort_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Define_as_default_search {
            get {
                return ResourceManager.GetString("Define_as_default_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an access?.
        /// </summary>
        public static string Dont_have_an_access {
            get {
                return ResourceManager.GetString("Dont_have_an_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en_EN {
            get {
                return ResourceManager.GetString("en-EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Metadata has not been properly completed.
        /// </summary>
        public static string Error_bad_metadata {
            get {
                return ResourceManager.GetString("Error_bad_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : Can&apos;t contact support by email.
        /// </summary>
        public static string Error_contact_support {
            get {
                return ResourceManager.GetString("Error_contact_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : Invalid data, map can&apos;t load extent.
        /// </summary>
        public static string Error_extent_map {
            get {
                return ResourceManager.GetString("Error_extent_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : Can&apos;t load log Manager.
        /// </summary>
        public static string Error_logManager {
            get {
                return ResourceManager.GetString("Error_logManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : Can&apos;t load log file.
        /// </summary>
        public static string Error_logs {
            get {
                return ResourceManager.GetString("Error_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy information could not be saved.
        /// </summary>
        public static string Error_proxy {
            get {
                return ResourceManager.GetString("Error_proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDE connection file.
        /// </summary>
        public static string FileSDE {
            get {
                return ResourceManager.GetString("FileSDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format_source {
            get {
                return ResourceManager.GetString("Format_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string fr_FR {
            get {
                return ResourceManager.GetString("fr-FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographic filter.
        /// </summary>
        public static string Geographic_filter {
            get {
                return ResourceManager.GetString("Geographic_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Geographic_type_contains {
            get {
                return ResourceManager.GetString("Geographic_type_contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersect.
        /// </summary>
        public static string Geographic_type_intersects {
            get {
                return ResourceManager.GetString("Geographic_type_intersects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whithin.
        /// </summary>
        public static string Geographic_type_within {
            get {
                return ResourceManager.GetString("Geographic_type_within", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geographical operator.
        /// </summary>
        public static string Geographical_operator_applied_to_the_filter {
            get {
                return ResourceManager.GetString("Geographical_operator_applied_to_the_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import access from a file :.
        /// </summary>
        public static string Import_access_from_a_file {
            get {
                return ResourceManager.GetString("Import_access_from_a_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file.
        /// </summary>
        public static string Import_File {
            get {
                return ResourceManager.GetString("Import_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSPIRE keywords.
        /// </summary>
        public static string INSPIRE_keywords {
            get {
                return ResourceManager.GetString("INSPIRE_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isogeo authentication settings.
        /// </summary>
        public static string Isogeo_authentication_settings {
            get {
                return ResourceManager.GetString("Isogeo_authentication_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isogeo login.
        /// </summary>
        public static string Isogeo_login {
            get {
                return ResourceManager.GetString("Isogeo_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (default).
        /// </summary>
        public static string Lang_default {
            get {
                return ResourceManager.GetString("Lang_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence.
        /// </summary>
        public static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map canvas.
        /// </summary>
        public static string Map_canvas {
            get {
                return ResourceManager.GetString("Map_canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Menu_Download {
            get {
                return ResourceManager.GetString("Menu_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load data.
        /// </summary>
        public static string Menu_load {
            get {
                return ResourceManager.GetString("Menu_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Menu_Metadata {
            get {
                return ResourceManager.GetString("Menu_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenCatalog.
        /// </summary>
        public static string Menu_OpenCatalog {
            get {
                return ResourceManager.GetString("Menu_OpenCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can contact support at &apos;support+arcgispro@isogeo.fr&apos;.
        /// </summary>
        public static string Message_contact_support {
            get {
                return ResourceManager.GetString("Message_contact_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested service is not compatible or has not been configured to work in ArcGis Pro.
        /// </summary>
        public static string Message_Data_Error {
            get {
                return ResourceManager.GetString("Message_Data_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not found.
        /// </summary>
        public static string Message_Data_file_not_found {
            get {
                return ResourceManager.GetString("Message_Data_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer not found.
        /// </summary>
        public static string Message_Data_layer_not_found {
            get {
                return ResourceManager.GetString("Message_Data_layer_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDE login file not configured in the &apos;Settings&apos; tab..
        /// </summary>
        public static string Message_Data_sde_not_configured {
            get {
                return ResourceManager.GetString("Message_Data_sde_not_configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name is undefined.
        /// </summary>
        public static string Message_Data_table_undefined {
            get {
                return ResourceManager.GetString("Message_Data_table_undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmanaged data type.
        /// </summary>
        public static string Message_Data_Type {
            get {
                return ResourceManager.GetString("Message_Data_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Message_Metadata_Advanced {
            get {
                return ResourceManager.GetString("Message_Metadata_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Message_Metadata_Contacts {
            get {
                return ResourceManager.GetString("Message_Metadata_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Message_Metadata_General {
            get {
                return ResourceManager.GetString("Message_Metadata_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geography.
        /// </summary>
        public static string Message_Metadata_Geography {
            get {
                return ResourceManager.GetString("Message_Metadata_Geography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Message_Metadata_History {
            get {
                return ResourceManager.GetString("Message_Metadata_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Message_Metadata_Licenses {
            get {
                return ResourceManager.GetString("Message_Metadata_Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID is mandatory.
        /// </summary>
        public static string Message_Query_authentication_id_mandatory {
            get {
                return ResourceManager.GetString("Message_Query_authentication_id_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion failed..
        /// </summary>
        public static string Message_Query_authentication_ko {
            get {
                return ResourceManager.GetString("Message_Query_authentication_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed. Please check your internet connection and try again..
        /// </summary>
        public static string Message_Query_authentication_ko_internet {
            get {
                return ResourceManager.GetString("Message_Query_authentication_ko_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID or SECRET.
        /// </summary>
        public static string Message_Query_authentication_ko_invalid {
            get {
                return ResourceManager.GetString("Message_Query_authentication_ko_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed. Please check your proxy parameters.
        /// </summary>
        public static string Message_Query_authentication_ko_proxy {
            get {
                return ResourceManager.GetString("Message_Query_authentication_ko_proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion is ok..
        /// </summary>
        public static string Message_Query_authentication_ok {
            get {
                return ResourceManager.GetString("Message_Query_authentication_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECRET must have 64 characters.
        /// </summary>
        public static string Message_Query_authentication_secret_mandatory {
            get {
                return ResourceManager.GetString("Message_Query_authentication_secret_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        public static string Message_Settings_save {
            get {
                return ResourceManager.GetString("Message_Settings_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created :.
        /// </summary>
        public static string Metadata_Advanced_create {
            get {
                return ResourceManager.GetString("Metadata_Advanced_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata properties.
        /// </summary>
        public static string Metadata_Advanced_details {
            get {
                return ResourceManager.GetString("Metadata_Advanced_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language :.
        /// </summary>
        public static string Metadata_Advanced_lang {
            get {
                return ResourceManager.GetString("Metadata_Advanced_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update :.
        /// </summary>
        public static string Metadata_Advanced_last_update {
            get {
                return ResourceManager.GetString("Metadata_Advanced_last_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Metadata_Advanced_owner {
            get {
                return ResourceManager.GetString("Metadata_Advanced_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other contacts.
        /// </summary>
        public static string Metadata_Contacts_others_contacts {
            get {
                return ResourceManager.GetString("Metadata_Contacts_others_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of contact.
        /// </summary>
        public static string Metadata_Contacts_points_contacts {
            get {
                return ResourceManager.GetString("Metadata_Contacts_points_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conformity :.
        /// </summary>
        public static string Metadata_General_conformity {
            get {
                return ResourceManager.GetString("Metadata_General_conformity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description :.
        /// </summary>
        public static string Metadata_General_description {
            get {
                return ResourceManager.GetString("Metadata_General_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords :.
        /// </summary>
        public static string Metadata_General_keywords {
            get {
                return ResourceManager.GetString("Metadata_General_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner :.
        /// </summary>
        public static string Metadata_General_owner {
            get {
                return ResourceManager.GetString("Metadata_General_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme :.
        /// </summary>
        public static string Metadata_General_themes {
            get {
                return ResourceManager.GetString("Metadata_General_themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format :.
        /// </summary>
        public static string Metadata_Geography_format {
            get {
                return ResourceManager.GetString("Metadata_Geography_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry type :.
        /// </summary>
        public static string Metadata_Geography_geometrytype {
            get {
                return ResourceManager.GetString("Metadata_Geography_geometrytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical informations.
        /// </summary>
        public static string Metadata_Geography_info {
            get {
                return ResourceManager.GetString("Metadata_Geography_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features count :.
        /// </summary>
        public static string Metadata_Geography_nbobjects {
            get {
                return ResourceManager.GetString("Metadata_Geography_nbobjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution :.
        /// </summary>
        public static string Metadata_Geography_resolution {
            get {
                return ResourceManager.GetString("Metadata_Geography_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale :.
        /// </summary>
        public static string Metadata_Geography_scale {
            get {
                return ResourceManager.GetString("Metadata_Geography_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification.
        /// </summary>
        public static string Metadata_Geography_specification {
            get {
                return ResourceManager.GetString("Metadata_Geography_specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRS :.
        /// </summary>
        public static string Metadata_Geography_srs {
            get {
                return ResourceManager.GetString("Metadata_Geography_srs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typology.
        /// </summary>
        public static string Metadata_Geography_typology {
            get {
                return ResourceManager.GetString("Metadata_Geography_typology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments :.
        /// </summary>
        public static string Metadata_History_comment {
            get {
                return ResourceManager.GetString("Metadata_History_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string Metadata_History_context {
            get {
                return ResourceManager.GetString("Metadata_History_context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date :.
        /// </summary>
        public static string Metadata_History_datecreate {
            get {
                return ResourceManager.GetString("Metadata_History_datecreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End validity :.
        /// </summary>
        public static string Metadata_History_endvalid {
            get {
                return ResourceManager.GetString("Metadata_History_endvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data history.
        /// </summary>
        public static string Metadata_History_history {
            get {
                return ResourceManager.GetString("Metadata_History_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update :.
        /// </summary>
        public static string Metadata_History_lastupdate {
            get {
                return ResourceManager.GetString("Metadata_History_lastupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modifications.
        /// </summary>
        public static string Metadata_History_lastupdatedata {
            get {
                return ResourceManager.GetString("Metadata_History_lastupdatedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string Metadata_History_method {
            get {
                return ResourceManager.GetString("Metadata_History_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start validity :.
        /// </summary>
        public static string Metadata_History_startvalid {
            get {
                return ResourceManager.GetString("Metadata_History_startvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated every :.
        /// </summary>
        public static string Metadata_History_updateevery {
            get {
                return ResourceManager.GetString("Metadata_History_updateevery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licences.
        /// </summary>
        public static string Metadata_Licences_licence {
            get {
                return ResourceManager.GetString("Metadata_Licences_licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitations.
        /// </summary>
        public static string Metadata_Licences_limitation {
            get {
                return ResourceManager.GetString("Metadata_Licences_limitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata owner.
        /// </summary>
        public static string Metadata_owner {
            get {
                return ResourceManager.GetString("Metadata_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata owner (default).
        /// </summary>
        public static string Metadata_owner_default {
            get {
                return ResourceManager.GetString("Metadata_owner_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Polygon.
        /// </summary>
        public static string MultiPolygon {
            get {
                return ResourceManager.GetString("MultiPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New search.
        /// </summary>
        public static string New_search {
            get {
                return ResourceManager.GetString("New_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No licence.
        /// </summary>
        public static string No_licence {
            get {
                return ResourceManager.GetString("No_licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NR.
        /// </summary>
        public static string NotReported {
            get {
                return ResourceManager.GetString("NotReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open online help.
        /// </summary>
        public static string Open_help {
            get {
                return ResourceManager.GetString("Open_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log file.
        /// </summary>
        public static string Open_log {
            get {
                return ResourceManager.GetString("Open_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open plugin credits.
        /// </summary>
        public static string Open_plugin_credits {
            get {
                return ResourceManager.GetString("Open_plugin_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        public static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        public static string Polygon {
            get {
                return ResourceManager.GetString("Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostGIS table.
        /// </summary>
        public static string PostGIS_table {
            get {
                return ResourceManager.GetString("PostGIS_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last search.
        /// </summary>
        public static string Previous_search {
            get {
                return ResourceManager.GetString("Previous_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Proxy_password {
            get {
                return ResourceManager.GetString("Proxy_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy information has been saved.
        /// </summary>
        public static string Proxy_saved {
            get {
                return ResourceManager.GetString("Proxy_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Settings.
        /// </summary>
        public static string Proxy_settings {
            get {
                return ResourceManager.GetString("Proxy_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy URL.
        /// </summary>
        public static string Proxy_url {
            get {
                return ResourceManager.GetString("Proxy_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Proxy_user {
            get {
                return ResourceManager.GetString("Proxy_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Search.
        /// </summary>
        public static string Quick_search {
            get {
                return ResourceManager.GetString("Quick_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick search settings.
        /// </summary>
        public static string Quick_search_settings {
            get {
                return ResourceManager.GetString("Quick_search_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exist..
        /// </summary>
        public static string Quicksearch_already_exist {
            get {
                return ResourceManager.GetString("Quicksearch_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quicksearch name.
        /// </summary>
        public static string Quicksearch_name {
            get {
                return ResourceManager.GetString("Quicksearch_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is mandatory..
        /// </summary>
        public static string Quicksearch_name_mandatory {
            get {
                return ResourceManager.GetString("Quicksearch_name_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New quicksearch.
        /// </summary>
        public static string Quicksearch_new {
            get {
                return ResourceManager.GetString("Quicksearch_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quicksearch new name.
        /// </summary>
        public static string Quicksearch_new_name {
            get {
                return ResourceManager.GetString("Quicksearch_new_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename quicksearch.
        /// </summary>
        public static string Quicksearch_rename {
            get {
                return ResourceManager.GetString("Quicksearch_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raster.
        /// </summary>
        public static string Raster {
            get {
                return ResourceManager.GetString("Raster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realization.
        /// </summary>
        public static string Realization {
            get {
                return ResourceManager.GetString("Realization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload last search.
        /// </summary>
        public static string Reload_last_search {
            get {
                return ResourceManager.GetString("Reload_last_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all input fields.
        /// </summary>
        public static string Reset_search {
            get {
                return ResourceManager.GetString("Reset_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type.
        /// </summary>
        public static string Resource_type {
            get {
                return ResourceManager.GetString("Resource_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources_ {
            get {
                return ResourceManager.GetString("Resources_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string Save_as {
            get {
                return ResourceManager.GetString("Save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search management.
        /// </summary>
        public static string Search_management {
            get {
                return ResourceManager.GetString("Search_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search settings.
        /// </summary>
        public static string Search_settings {
            get {
                return ResourceManager.GetString("Search_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms search.
        /// </summary>
        public static string Search_terms {
            get {
                return ResourceManager.GetString("Search_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_word {
            get {
                return ResourceManager.GetString("Search_word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set plugin authentication.
        /// </summary>
        public static string Set_pluggin_authentication {
            get {
                return ResourceManager.GetString("Set_pluggin_authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting direction.
        /// </summary>
        public static string Sorting_direction {
            get {
                return ResourceManager.GetString("Sorting_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting method.
        /// </summary>
        public static string Sorting_method {
            get {
                return ResourceManager.GetString("Sorting_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Sorting_method_ascending {
            get {
                return ResourceManager.GetString("Sorting_method_ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data created.
        /// </summary>
        public static string Sorting_method_created {
            get {
                return ResourceManager.GetString("Sorting_method_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Sorting_method_descending {
            get {
                return ResourceManager.GetString("Sorting_method_descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata created.
        /// </summary>
        public static string Sorting_method_metadata_created {
            get {
                return ResourceManager.GetString("Sorting_method_metadata_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata modified.
        /// </summary>
        public static string Sorting_method_metadata_modified {
            get {
                return ResourceManager.GetString("Sorting_method_metadata_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data modified.
        /// </summary>
        public static string Sorting_method_modified {
            get {
                return ResourceManager.GetString("Sorting_method_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevance.
        /// </summary>
        public static string Sorting_method_relevance {
            get {
                return ResourceManager.GetString("Sorting_method_relevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical order.
        /// </summary>
        public static string Sorting_method_title {
            get {
                return ResourceManager.GetString("Sorting_method_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown geometry.
        /// </summary>
        public static string Unknown_geometry {
            get {
                return ResourceManager.GetString("Unknown_geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFS.
        /// </summary>
        public static string WFS {
            get {
                return ResourceManager.GetString("WFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMS.
        /// </summary>
        public static string WMS {
            get {
                return ResourceManager.GetString("WMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMTS.
        /// </summary>
        public static string WMTS {
            get {
                return ResourceManager.GetString("WMTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
